#-*- mode: ruby -*-

packaging :pom # use pom packaging to avoid building war file on test run

profile(:integration) do |t|
  t.build.default_goal 'verify'

  t.plugin(:jruby, '${jruby.plugins.version}').in_phase('integration-test').execute_goal(:jruby).with :file => 'load_index.rb'

  t.plugin('org.mortbay.jetty:jetty-maven-plugin', '${jetty.version}') do |j|
    j.with(:stopKey => :foo, :stopPort => 9999)
    j.in_phase('pre-integration-test').execute_goal(:run).with(:daemon => true)
    j.in_phase('post-integration-test').execute_goal(:stop)
  end
end

# vim: syntax=Ruby
