#-*- mode: ruby -*-

jar("org.jruby.rack:jruby-rack", '1.1.13.1')
if defined?( JRUBY_VERSION ) && JRUBY_VERSION =~ /^1\.7\./
  jar("org.jruby:jruby-core", "${jruby.version}")
else
  jar("org.jruby:jruby-complete", "${jruby.version}")
end

# lock down versions
properties['jruby.version'] = '1.7.2'
properties['jruby.plugins.version'] = '0.29.3'
properties['jetty.version'] = '8.1.9.v20130131'

# vim: syntax=Ruby
